// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NegoSudApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NegoSudApi.Migrations
{
    [DbContext(typeof(NegoSudDbContext))]
    [Migration("20230226195829_New_One")]
    partial class NewOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NegoSudApi.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_address_city_id");

                    b.HasIndex("SupplierId")
                        .IsUnique()
                        .HasDatabaseName("ix_address_supplier_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_address_user_id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Bottle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AlcoholPercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("alcohol_percentage");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("CustomerPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("customer_price");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Picture")
                        .HasColumnType("text")
                        .HasColumnName("picture");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("integer")
                        .HasColumnName("producer_id");

                    b.Property<int?>("QuantityMinimumToOrder")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_minimum_to_order");

                    b.Property<decimal?>("SupplierPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("supplier_price");

                    b.Property<int?>("ThresholdToOrder")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_to_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("VatId")
                        .HasColumnType("integer")
                        .HasColumnName("vat_id");

                    b.Property<decimal?>("Volume")
                        .HasColumnType("numeric")
                        .HasColumnName("volume");

                    b.Property<int?>("WineLabelId")
                        .HasColumnType("integer")
                        .HasColumnName("wine_label_id");

                    b.Property<string>("WineType")
                        .HasColumnType("text")
                        .HasColumnName("wine_type");

                    b.Property<int?>("YearProduced")
                        .HasColumnType("integer")
                        .HasColumnName("year_produced");

                    b.HasKey("Id")
                        .HasName("pk_bottle");

                    b.HasIndex("ProducerId")
                        .HasDatabaseName("ix_bottle_producer_id");

                    b.HasIndex("VatId")
                        .HasDatabaseName("ix_bottle_vat_id");

                    b.HasIndex("WineLabelId")
                        .HasDatabaseName("ix_bottle_wine_label_id");

                    b.HasIndex("WineType")
                        .HasDatabaseName("ix_bottle_wine_type");

                    b.ToTable("Bottle", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleGrape", b =>
                {
                    b.Property<int>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottle_id");

                    b.Property<int>("GrapeId")
                        .HasColumnType("integer")
                        .HasColumnName("grape_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<decimal?>("GrapePercentage")
                        .HasColumnType("numeric")
                        .HasColumnName("grape_percentage");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("BottleId", "GrapeId")
                        .HasName("pk_bottle_grape");

                    b.HasIndex("GrapeId")
                        .HasDatabaseName("ix_bottle_grape_grape_id");

                    b.ToTable("BottleGrape", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleStorageLocation", b =>
                {
                    b.Property<int>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottle_id");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_location_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("BottleId", "StorageLocationId")
                        .HasName("pk_bottle_storage_location");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("ix_bottle_storage_location_storage_location_id");

                    b.ToTable("BottleStorageLocation", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleSupplier", b =>
                {
                    b.Property<int>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottle_id");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("BottleId", "SupplierId")
                        .HasName("pk_bottle_supplier");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_bottle_supplier_supplier_id");

                    b.ToTable("BottleSupplier", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("integer")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_city_country_id");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_country");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("Date_Delivery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_delivery");

                    b.Property<DateTime?>("Date_Order")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_order");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_address_id");

                    b.Property<int?>("DeliveryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_customer_order");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_order_customer_id");

                    b.HasIndex("DeliveryAddressId")
                        .HasDatabaseName("ix_customer_order_delivery_address_id");

                    b.ToTable("CustomerOrder", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottle_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<int?>("CustomerOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_order_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_customer_order_line");

                    b.HasIndex("BottleId")
                        .HasDatabaseName("ix_customer_order_line_bottle_id");

                    b.HasIndex("CustomerOrderId")
                        .HasDatabaseName("ix_customer_order_line_customer_order_id");

                    b.ToTable("CustomerOrderLine", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrderLineStorageLocation", b =>
                {
                    b.Property<int>("CustomerOrderLineId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_order_line_id");

                    b.Property<int>("StorageLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("storage_location_id");

                    b.HasKey("CustomerOrderLineId", "StorageLocationId")
                        .HasName("pk_customer_order_line_storage_location");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("ix_customer_order_line_storage_location_storage_location_id");

                    b.ToTable("CustomerOrderLineStorageLocation", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Grape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("GrapeType")
                        .HasColumnType("text")
                        .HasColumnName("grape_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_grape");

                    b.ToTable("Grape", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_permission");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.PermissionRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_permission_role");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_permission_role_permission_id");

                    b.ToTable("PermissionRole", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_producer");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_producer_address_id");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_producer_region_id");

                    b.ToTable("Producer", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_region");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_region_country_id");

                    b.ToTable("Region", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.StorageLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_storage_location");

                    b.ToTable("StorageLocation", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateDelivery")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_delivery");

                    b.Property<DateTime?>("DateOrder")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_order");

                    b.Property<int?>("DeliveryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_status");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_order");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_order_supplier_id");

                    b.ToTable("SupplierOrder", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.SupplierOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BottleId")
                        .HasColumnType("integer")
                        .HasColumnName("bottle_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("SupplierOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("supplier_order_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_supplier_order_line");

                    b.HasIndex("BottleId")
                        .HasDatabaseName("ix_supplier_order_line_bottle_id");

                    b.HasIndex("SupplierOrderId")
                        .HasDatabaseName("ix_supplier_order_line_supplier_order_id");

                    b.ToTable("SupplierOrderLine", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.VAT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_vat");

                    b.ToTable("VAT", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.WineLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(0)
                        .HasColumnType("timestamp(0) with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_wine_label");

                    b.ToTable("WineLabel", (string)null);
                });

            modelBuilder.Entity("NegoSudApi.Models.Address", b =>
                {
                    b.HasOne("NegoSudApi.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .HasConstraintName("fk_address_city_city_id");

                    b.HasOne("NegoSudApi.Models.Supplier", "Supplier")
                        .WithOne("Address")
                        .HasForeignKey("NegoSudApi.Models.Address", "SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_address_suppliers_supplier_id");

                    b.HasOne("NegoSudApi.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_address_users_user_id");

                    b.Navigation("City");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NegoSudApi.Models.Bottle", b =>
                {
                    b.HasOne("NegoSudApi.Models.Producer", "Producer")
                        .WithMany("Bottles")
                        .HasForeignKey("ProducerId")
                        .HasConstraintName("fk_bottle_producers_producer_id");

                    b.HasOne("NegoSudApi.Models.VAT", "Vat")
                        .WithMany("Bottles")
                        .HasForeignKey("VatId")
                        .HasConstraintName("fk_bottle_vat_vat_id");

                    b.HasOne("NegoSudApi.Models.WineLabel", "WineLabel")
                        .WithMany("Bottles")
                        .HasForeignKey("WineLabelId")
                        .HasConstraintName("fk_bottle_wine_labels_wine_label_id");

                    b.Navigation("Producer");

                    b.Navigation("Vat");

                    b.Navigation("WineLabel");
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleGrape", b =>
                {
                    b.HasOne("NegoSudApi.Models.Bottle", "Bottle")
                        .WithMany("BottleGrapes")
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_grape_bottle_bottle_id");

                    b.HasOne("NegoSudApi.Models.Grape", "Grape")
                        .WithMany("BottleGrapes")
                        .HasForeignKey("GrapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_grape_grapes_grape_id");

                    b.Navigation("Bottle");

                    b.Navigation("Grape");
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleStorageLocation", b =>
                {
                    b.HasOne("NegoSudApi.Models.Bottle", "Bottle")
                        .WithMany("BottleStorageLocations")
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_storage_location_bottle_bottle_id");

                    b.HasOne("NegoSudApi.Models.StorageLocation", "StorageLocation")
                        .WithMany("BottleStorageLocations")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_storage_location_storage_location_storage_location_id");

                    b.Navigation("Bottle");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("NegoSudApi.Models.BottleSupplier", b =>
                {
                    b.HasOne("NegoSudApi.Models.Bottle", "Bottle")
                        .WithMany("BottleSuppliers")
                        .HasForeignKey("BottleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_supplier_bottle_bottle_id");

                    b.HasOne("NegoSudApi.Models.Supplier", "Supplier")
                        .WithMany("BottleSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bottle_supplier_suppliers_supplier_id");

                    b.Navigation("Bottle");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NegoSudApi.Models.City", b =>
                {
                    b.HasOne("NegoSudApi.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_city_country_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrder", b =>
                {
                    b.HasOne("NegoSudApi.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_customer_order_users_customer_id");

                    b.HasOne("NegoSudApi.Models.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .HasConstraintName("fk_customer_order_address_delivery_address_id");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrderLine", b =>
                {
                    b.HasOne("NegoSudApi.Models.Bottle", "Bottle")
                        .WithMany()
                        .HasForeignKey("BottleId")
                        .HasConstraintName("fk_customer_order_line_bottle_bottle_id");

                    b.HasOne("NegoSudApi.Models.CustomerOrder", "CustomerOrder")
                        .WithMany("Lines")
                        .HasForeignKey("CustomerOrderId")
                        .HasConstraintName("fk_customer_order_line_customer_order_customer_order_id");

                    b.Navigation("Bottle");

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrderLineStorageLocation", b =>
                {
                    b.HasOne("NegoSudApi.Models.CustomerOrderLine", "CustomerOrderLine")
                        .WithMany("CustomerOrderLineStorageLocations")
                        .HasForeignKey("CustomerOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_order_line_storage_location_customer_order_line_customer");

                    b.HasOne("NegoSudApi.Models.StorageLocation", "StorageLocation")
                        .WithMany("CustomerOrderLineStorageLocations")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_order_line_storage_location_storage_location_storage_lo");

                    b.Navigation("CustomerOrderLine");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("NegoSudApi.Models.PermissionRole", b =>
                {
                    b.HasOne("NegoSudApi.Models.Permission", "Permission")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_role_permissions_permission_id");

                    b.HasOne("NegoSudApi.Models.Role", "Role")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permission_role_role_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NegoSudApi.Models.Producer", b =>
                {
                    b.HasOne("NegoSudApi.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .HasConstraintName("fk_producer_addresses_address_id");

                    b.HasOne("NegoSudApi.Models.Region", "Region")
                        .WithMany("Producers")
                        .HasForeignKey("RegionId")
                        .HasConstraintName("fk_producer_regions_region_id");

                    b.Navigation("Address");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("NegoSudApi.Models.Region", b =>
                {
                    b.HasOne("NegoSudApi.Models.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_region_country_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("NegoSudApi.Models.SupplierOrder", b =>
                {
                    b.HasOne("NegoSudApi.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("fk_supplier_order_suppliers_supplier_id");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("NegoSudApi.Models.SupplierOrderLine", b =>
                {
                    b.HasOne("NegoSudApi.Models.Bottle", "Bottle")
                        .WithMany("SupplierOrderLines")
                        .HasForeignKey("BottleId")
                        .HasConstraintName("fk_supplier_order_line_bottle_bottle_id");

                    b.HasOne("NegoSudApi.Models.SupplierOrder", "SupplierOrder")
                        .WithMany("Lines")
                        .HasForeignKey("SupplierOrderId")
                        .HasConstraintName("fk_supplier_order_line_supplier_order_supplier_order_id");

                    b.Navigation("Bottle");

                    b.Navigation("SupplierOrder");
                });

            modelBuilder.Entity("NegoSudApi.Models.User", b =>
                {
                    b.HasOne("NegoSudApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_user_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NegoSudApi.Models.Bottle", b =>
                {
                    b.Navigation("BottleGrapes");

                    b.Navigation("BottleStorageLocations");

                    b.Navigation("BottleSuppliers");

                    b.Navigation("SupplierOrderLines");
                });

            modelBuilder.Entity("NegoSudApi.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("NegoSudApi.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NegoSudApi.Models.CustomerOrderLine", b =>
                {
                    b.Navigation("CustomerOrderLineStorageLocations");
                });

            modelBuilder.Entity("NegoSudApi.Models.Grape", b =>
                {
                    b.Navigation("BottleGrapes");
                });

            modelBuilder.Entity("NegoSudApi.Models.Permission", b =>
                {
                    b.Navigation("PermissionRoles");
                });

            modelBuilder.Entity("NegoSudApi.Models.Producer", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("NegoSudApi.Models.Region", b =>
                {
                    b.Navigation("Producers");
                });

            modelBuilder.Entity("NegoSudApi.Models.Role", b =>
                {
                    b.Navigation("PermissionRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NegoSudApi.Models.StorageLocation", b =>
                {
                    b.Navigation("BottleStorageLocations");

                    b.Navigation("CustomerOrderLineStorageLocations");
                });

            modelBuilder.Entity("NegoSudApi.Models.Supplier", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("BottleSuppliers");
                });

            modelBuilder.Entity("NegoSudApi.Models.SupplierOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("NegoSudApi.Models.User", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("NegoSudApi.Models.VAT", b =>
                {
                    b.Navigation("Bottles");
                });

            modelBuilder.Entity("NegoSudApi.Models.WineLabel", b =>
                {
                    b.Navigation("Bottles");
                });
#pragma warning restore 612, 618
        }
    }
}
